# Generated by Django 4.0.1 on 2022-01-07 12:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('summary', ckeditor.fields.RichTextField()),
                ('description_col_1', ckeditor.fields.RichTextField()),
                ('description_col_2', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('image', models.ImageField(upload_to='courses_image')),
                ('summary', ckeditor.fields.RichTextField()),
                ('description_col_1', ckeditor.fields.RichTextField()),
                ('description_col_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
