# Generated by Django 4.0.1 on 2022-01-07 16:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', ckeditor.fields.RichTextField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facts', ckeditor.fields.RichTextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=256, null=True, verbose_name='Country')),
                ('street', models.CharField(blank=True, max_length=256, null=True, verbose_name='Street')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('why_choose_video', models.URLField(blank=True, null=True)),
                ('hero_video', models.URLField(blank=True, null=True)),
                ('hero_video_poster', models.ImageField(blank=True, null=True, upload_to='why_choose_video_poster')),
                ('apply', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='home/backgrounds')),
                ('apply_button_text', models.CharField(blank=True, help_text='Apply Button Text', max_length=250, null=True)),
            ],
            options={
                'ordering': ('-last_modified', '-created_at'),
            },
        ),
    ]
