# Generated by Django 4.0.1 on 2022-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_video_poster',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='why_choose_video',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='youtube_link',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
